[package]
name = "pwd_validate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
zip = "2.1.5"

[lib]
name = "pwd_validate"
crate_type = ["rlib", "cdylib"]